### ISSUE TITLE
alpha cannot be resolved or is not a field

### ISSUE THREAD

**Issue by AzzaDeveloper** [AzzaDeveloper/prosu#2]
https://i.imgur.com/ythASuJ.png 
f_drawObj.pde:2:0:2:0: alpha cannot be resolved or is not a field

_Originally posted by @oSumAtrIX in https://github.com/AzzaDeveloper/prosu/issues/1#issuecomment-562947454_

**Comment by AzzaDeveloper** [comment]
@oSumaTrix what was the beatmap that you chose?

**Comment by oSumAtrIX** [comment]
I tried:
"B:/Spiele/osu!/Songs/Panda Eyes - ILY (Part II)",
"B:/Spiele/osu!/Songs/",
"B:/Spiele/osu!/Songs/239727 IA - Setsuna Drive"

The game does not launch at all

**Comment by AzzaDeveloper** [comment]
Haven't encounter this before. Runs fine on two other PCs. I'll have a look, thanks.

So you got to the song selection screen, but you can't start a song?

**Comment by oSumAtrIX** [comment]
No, check the screenshot, its right after I launch the command

**Comment by AzzaDeveloper** [comment]
Unknown reason, a fresh clone was able to solved it.
